# -*- coding: utf-8 -*-
"""PIA CONTAA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14eX0TqwGzZJBw229HX7QnP-xK7Nf6QUH
"""

from importlib import invalidate_caches
from prettytable import PrettyTable

# 1. PRESUPUESTOS DE VENTAS
  # Producto A
print("PRESUPUESTO DE VENTAS")
print("-"*40)
print("\t\tProducto A")
print("-"*40)
print("PRIMER SEMESTRE")
ventasEsperadas_A1 = int(input("No. de Unidades: "))
precioA_Sem1 = int(input("Precio: "))

print("-"*40)
print("SEGUNDO SEMESTRE")
ventasEsperadas_A2 = int(input("No. de Unidades: "))
precioA_Sem2 = int(input("Precio: "))

  # Creación de Tabla
print("")
t = PrettyTable(['Producto A.','PRIMER SEMESTRE','SEGUNDO SEMESTRE'])
t.add_row([" Ventas Esperadas  ",ventasEsperadas_A1, ventasEsperadas_A2])
t.add_row(["(X)Precio de Venta ",precioA_Sem1, precioA_Sem2])
t.add_row(["($)Ventas Esperadas",(ventasEsperadas_A1*precioA_Sem1), (ventasEsperadas_A2*precioA_Sem2)])
print(t)
ventas_A = (ventasEsperadas_A1*precioA_Sem1) + (ventasEsperadas_A2*precioA_Sem2)
print(" TOTAL DEL PRODUCTO A. = $", ventas_A)
print("\n")

  # Producto B
print("-"*40)
print("\t\tProducto B")
print("-"*40)
print("PRIMER SEMESTRE")
ventasEsperadas_B1 = int(input("No. de Unidades: "))
precioB_Sem1 = int(input("Precio: "))

print("-"*40)
print("SEGUNDO SEMESTRE")
ventasEsperadas_B2 = int(input("No. de Unidades: "))
precioB_Sem2 = int(input("Precio: "))

print("")
t = PrettyTable(['Producto B.','PRIMER SEMESTRE','SEGUNDO SEMESTRE'])
t.add_row([" Ventas Esperadas  ",ventasEsperadas_B1,ventasEsperadas_B2])
t.add_row(["(X)Precio de Venta ",precioB_Sem1,precioB_Sem2])
t.add_row(["($)Ventas Esperadas",(ventasEsperadas_B1*precioB_Sem1),(ventasEsperadas_B2*precioB_Sem2)])
print(t)
ventas_B =(ventasEsperadas_B1*precioB_Sem1)+(ventasEsperadas_B2*precioB_Sem2)
print(" TOTAL DEL PRODUCTO B. = $ ",ventas_B)
print("\n")


  # 2. SALDO DE CLIENTES Y FLUJO DE ENTRADA
ventaTotal = ventas_A + ventas_B

print("-"*30)
print(f"\tSALDO CLIENTES")
print("-"*30)
saldoCliente = int(input("Saldo Clientes 2020:  $ "))
print(f"Saldo Cliente 2021:   $ {ventaTotal}")
saldoTotal = saldoCliente + ventaTotal
print(f"Saldo Total:          $ {saldoTotal}")
print("-"*30)

print("\tENTRADAS")
print("-"*30)
print("Cobranza 2020:       $ ", saldoCliente)
print("Cobranza 2021:       $ ", int(ventaTotal * .8)) # Se cobro el 80%.
entradas = saldoCliente + int((ventaTotal * .8))
print(f"Total de Entradas:   $  {entradas} ")
print("-"*30)
print(f"Saldo Clientes:      $  {int(ventaTotal * .2)}") # 20% de Deuda


# 3. PRESUPUESTO DE PRODUCCIÓN
# PRODUCTO A.
  # Inventario
inicial_A1 = 10000 
final_A2 = 7000
  # Unidades a Producir
udsProducir_A1 = ventasEsperadas_A1 + inicial_A1 - inicial_A1
udsProducir_A2 = ventasEsperadas_A2 + final_A2 - inicial_A1

# PRODUCTO B.
  # Inventario.
inicial_B1 = 5000 
final_B2 = 3000
  # Unidades a Producir
udsProducir_B1 = ventasEsperadas_B1 + inicial_B1 - inicial_B1
udsProducir_B2 = ventasEsperadas_B2 + final_B2 - inicial_B1

print("\n")
print("PRESUPUESTO DE PRODUCCION")
print("-"*60)
print("   Producto A.")
t = PrettyTable(['','PRIMER SEMESTRE','SEGUNDO SEMESTRE'])
t.add_row(["  Unidades a Vender ", ventasEsperadas_A1, ventasEsperadas_A2])
t.add_row(["(+) Inventario Final", inicial_A1, final_A2])
t.add_row(["(=) Total Unidades. ", (ventasEsperadas_A1 + inicial_A1), (ventasEsperadas_A2 + final_A2)])
t.add_row(["(-) Invent. Inicial ", inicial_A1, inicial_A1])
t.add_row(["(=) Uds. a Producir ", udsProducir_A1, udsProducir_A2])
print(t)
print("\n")

print("PRESUPUESTO DE PRODUCCION")
print("-"*60)
print("   Producto B.")
t = PrettyTable(['','PRIMER SEMESTRE','SEGUNDO SEMESTRE'])
t.add_row(["  Unidades a Vender ", ventasEsperadas_B1,ventasEsperadas_B2])
t.add_row(["(+) Inventario Final", inicial_B1,final_B2])
t.add_row(["(=) Total Unidades  ", (ventasEsperadas_B1 + inicial_B1),(ventasEsperadas_B2 + final_B2)])
t.add_row(["(-) Invent. Inicial ", inicial_B1,inicial_B1])
t.add_row(["(=) Uds. a Producir ", udsProducir_B1,udsProducir_B2])
print(t)
print("\n")


#4. PRESUPUESTO DE REQUERIMIENTO DE MATERIALES
print("REQUERIMIENTOS DE MATERIALES")
print("-"*60)
print("Producto A. ")
mat1_A=int(input("Cantidad Material 1: "))
mat2_A=int(input("Cantidad Material 2: "))
mat3_A=int(input("Cantidad Material 3: "))

print("-"*60)
print("Producto B. ")
mat1_B=int(input("Cantidad Material 1: "))
mat2_B=int(input("Cantidad Material 2: "))
mat3_B=int(input("Cantidad Material 3: "))

#Material Requerido por PRODUCTO
  # Producto A. 1er Semestre
mat1_Asem1 = mat1_A * udsProducir_A1
mat2_Asem1 = mat2_A * udsProducir_A1
mat3_Asem1 = mat3_A * udsProducir_A1
  # Producto A. 2do Semestre
mat1_Asem2 = mat1_A * udsProducir_A2
mat2_Asem2 = mat2_A * udsProducir_A2
mat3_Asem2 = mat3_A * udsProducir_A2

  # Producto B. 1er Semestre
mat1_Bsem1 = mat1_B * udsProducir_B1
mat2_Bsem1 = mat2_B * udsProducir_B1
mat3_Bsem1 = mat3_B * udsProducir_B1
  # Producto B. 2do Semestre
mat1_Bsem2 = mat1_B * udsProducir_B2
mat2_Bsem2 = mat2_B * udsProducir_B2
mat3_Bsem2 = mat3_B * udsProducir_B2

print("\n")
print("PRESUPUESTO DE REQ. DE MATERIAL")
print("-"*60)
print("   Producto A.")
t = PrettyTable(['','PRIMER SEMESTRE','SEGUNDO SEMESTRE'])
t.add_row(["Uds. a Producir", udsProducir_A1, udsProducir_A2])
t.add_row(["Material 1     ", mat1_A, mat1_A])
t.add_row(["Material 2     ", mat2_A, mat2_A])
t.add_row(["Material 3     ", mat3_A, mat3_A])
t.add_row(["Total Mat.1    ", mat1_Asem1, mat1_Asem2 ])
t.add_row(["Total Mat.2    ", mat2_Asem1, mat2_Asem2])
t.add_row(["Total Mat.3    ", mat3_Asem1, mat3_Asem2])
print(t)
print("\n")

print("-"*60)
print("   Producto B.")
t = PrettyTable(['','PRIMER SEMESTRE','SEGUNDO SEMESTRE'])
t.add_row(["Uds. a Producir", udsProducir_B1, udsProducir_B2])
t.add_row(["Material 1     ", mat3_B, mat3_B])
t.add_row(["Material 2     ", mat2_B, mat2_B])
t.add_row(["Material 3     ", mat3_B, mat3_B])
t.add_row(["Total Mat.1    ", mat1_Bsem1, mat1_Bsem2])
t.add_row(["Total Mat.2    ", mat2_Bsem1, mat2_Bsem2])
t.add_row(["Total Mat.3    ", mat3_Bsem1, mat3_Bsem2])
print(t)
print("\n")


#5. PRESUPUESTO DE COMPRA DE MATERIALES.
print("PRESUESTO COMPRA DE MATERIALES.")
print("-"*60)
  # Inventarios.
inicialMat1 = 10000
finalMat1 = 8000

inicialMat2 = 15000
finalMat2 = 4000

inicialMat3 = 15000
finalMat3 = 3000

# Material Requerido Por SEMESTRE
  # 1er Semestre
mat1_Sem1= mat1_Asem1 + mat1_Bsem1
mat2_Sem1= mat2_Asem1 + mat2_Bsem1
mat3_Sem1= mat3_Asem1 + mat3_Bsem1
  # 2do Semestre
mat1_Sem2= mat1_Asem1 + mat1_Bsem1
mat2_Sem2= mat2_Asem1 + mat2_Bsem1
mat3_Sem2= mat3_Asem1 + mat3_Bsem1

# Precio de Compra
print("MATERIAL 1.")
print("-"*60)
print("Precio de Compra.")
mat1Precio_Sem1 = int(input("1er Semestre:  "))
mat1Precio_Sem2 = int(input("2do Semestre:  "))
print("")

print("MATERIAL 2.")
print("-"*60)
print("Precio de Compra.")
mat2Precio_Sem1 = int(input("1er Semestre:  "))
mat2Precio_Sem2 = int(input("2do Semestre:  "))
print("")

print("MATERIAL 3.")
print("-"*60)
print("Precio de Compra.")
mat3Precio_Sem1 = int(input("1er Semestre:  "))
mat3Precio_Sem2 = int(input("2do Semestre:  "))
print("")

# Costo del Material Total
  # Material 1.
mat1Total_Sem1 = (mat1_Sem1 + inicialMat1 - inicialMat1) * mat1Precio_Sem1
mat1Total_Sem2 = (mat1_Sem2 + inicialMat2 - inicialMat2) * mat1Precio_Sem2
  # Material 2.
mat2Total_Sem1 = (mat2_Sem1 + inicialMat2 - inicialMat2) * mat2Precio_Sem1
mat2Total_Sem2 = (mat2_Sem2 + inicialMat2 - inicialMat2) * mat2Precio_Sem2
  # Material 3.
mat3Total_Sem1 = (mat3_Sem1 + inicialMat3 - inicialMat3) * mat3Precio_Sem1
mat3Total_Sem2 = (mat3_Sem2 + inicialMat3 - inicialMat3) * mat3Precio_Sem2

print("\n")
print("PRESUESTO COMPRA DE MATERIALES.")
print("-"*60)
print("   Material 1.")
t = PrettyTable(['','PRIMER SEMESTRE','SEGUNDO SEMESTRE'])
t.add_row(["  Requerim. Material  ", mat1_Sem1, mat1_Sem2])
t.add_row(["(+) Inventario Final  ", inicialMat1, finalMat1])
t.add_row(["(=) Total Material    ", (mat1_Sem1 + inicialMat1), (mat1_Sem2 + finalMat1) ])
t.add_row(["(-) Inventario Inicial", inicialMat1, inicialMat1])
t.add_row(["(=) Material a comprar", (mat1_Sem1 + inicialMat1 - inicialMat1), (mat1_Sem2 + finalMat1 - inicialMat1) ])
t.add_row(["(*) Precio de Compra  ", mat1Precio_Sem1, mat1Precio_Sem2])
t.add_row(["(=) Material Total $  ", mat1Total_Sem1, mat1Total_Sem2])
print(t)
print("\n")

print("-"*60)
print("PRESUESTO COMPRA DE MATERIALES.")
print("   Material 2.")
t = PrettyTable(['','PRIMER SEMESTRE','SEGUNDO SEMESTRE'])
t.add_row(["  Requerim. Material  ", mat2_Sem1, mat2_Sem2])
t.add_row(["(+) Inventario Final  ", inicialMat2, finalMat2])
t.add_row(["(=) Total Material    ", (mat2_Sem1 + inicialMat2), (mat2_Sem2 + finalMat2)])
t.add_row(["(-) Inventario Inicial", inicialMat2, inicialMat2])
t.add_row(["(=) Material a comprar", (mat2_Sem1 + inicialMat2 - inicialMat2), (mat2_Sem2 + finalMat2 - inicialMat2) ])
t.add_row(["(*) Precio de Compra  ",mat2Precio_Sem1, mat2Precio_Sem2])
t.add_row(["(=) Material Total    ",mat2Total_Sem1, mat2Total_Sem2])
print(t)
print("\n")

print("-"*60)
print("PRESUESTO COMPRA DE MATERIALES.")
print("   Material 3.")
t = PrettyTable(['','PRIMER SEMESTRE','SEGUNDO SEMESTRE'])
t.add_row(["  Requerim. Material  ", mat3_Sem1, mat3_Sem2])
t.add_row(["(+) Inventario Final  ", inicialMat3, finalMat3])
t.add_row(["(=) Total Material    ", (mat3_Sem1 + inicialMat3), (mat3_Sem2 + finalMat3)])
t.add_row(["(-) Inventario Inicial", inicialMat3, inicialMat3])
t.add_row(["(=) Material a comprar", (mat3_Sem1 + inicialMat3 - inicialMat3), (mat3_Sem2 + finalMat3 - inicialMat3) ])
t.add_row(["(*) Precio de Compra  ",mat3Precio_Sem1, mat3Precio_Sem2])
t.add_row(["(=) Material Total    ",mat3Total_Sem1, mat3Total_Sem2])
print(t)
print("\n")


#6. SALDO DE PROVEEDORES Y FLUJO DE SALIDAS.

materialTOTAL = mat1Total_Sem2 + mat1Total_Sem2 + mat2Total_Sem2 + mat2Total_Sem2 + mat3Total_Sem1 + mat3Total_Sem2

print("-"*40)
print(f"\tSALDO PROVEEDORES ")
print("-"*40)
saldoProv = int(input("Saldo Proveedores:      $ "))
print("Compras 2021:           $", materialTOTAL)
total_proveedores= (saldoProv + materialTOTAL)
print(f"Saldo Proveedores:      $ {total_proveedores}")
print("-"*40)

print("SALIDA DE EFECTIVO")
print("-"*40)
print("Pago Proveedores 2020:  $ ", saldoProv)
print("Pago Proveedores 2021:  $ ", int(saldoProv * .6))
print("-"*40)
print(f"Saldo Proveedores:     $ {int(saldoProv * .4)}")
print("\n")


#7. PRESUPUESTO DE MANO DE OBRA.
print("PRESUPUESTO DE MANO DE OBRA. ")
print("-"*40)
precioHora = int(input("Precio por Hora:  "))
print("-"*40)
cantHoras_A = int(input("PRODUCTO A. Horas de Mano de Obra :  "))
cantHoras_B = int(input("PRODUCTO A. Horas de Mano de Obra :  "))
print("\n")

costoMO_Asem1 = (udsProducir_A1 * cantHoras_A)*precioHora
costoMO_Asem2 = (udsProducir_A2 * cantHoras_A)*precioHora
costoMO_Bsem1 = (udsProducir_B1 * cantHoras_B)*precioHora
costoMO_Bsem2 = (udsProducir_B2 * cantHoras_B)*precioHora

print("PRESUPUESTO DE MANO DE OBRA. ")
print("-"*60)
print("   Producto A.")
t = PrettyTable(['','PRIMER SEMESTRE','SEGUNDO SEMESTRE'])
t.add_row(["Uds. a Producir  ", udsProducir_A1, udsProducir_A2])
t.add_row(["(x) Horas M. Obra", cantHoras_A, cantHoras_A])
t.add_row(["(=) Total Horas  ", (udsProducir_A1 * cantHoras_A),(udsProducir_A2 * cantHoras_A)])
t.add_row(["(x) Precio x Hora", precioHora, precioHora])
t.add_row(["(=) Costo de M.O.", costoMO_Asem1, costoMO_Asem2 ])
print(t)
print("\n")

print("PRESUPUESTO DE MANO DE OBRA. ")
print("   Producto B.")
t = PrettyTable(['','PRIMER SEMESTRE','SEGUNDO SEMESTRE'])
t.add_row(["Uds. a Producir    ", udsProducir_B1, udsProducir_B2])
t.add_row(["(x) Horas de M.Obra", cantHoras_B, cantHoras_B])
t.add_row(["(=) Total Horas    ", (udsProducir_B1 * cantHoras_B),(udsProducir_B2 * cantHoras_B)])
t.add_row(["(x) Precio x Hora  ", precioHora, precioHora])
t.add_row(["(=) Costo de M.O.  ", costoMO_Bsem1, costoMO_Bsem2])
print(t)
print("\n")

#8. PRESUPUESTO DE GASTOS INDIRECTOS DE FABRICACIÓN.
deprec_GIF = 100000 # Anuales
seguros_GIF = 50000 #Anuales
mant_GIF = 75000 # 45% por el primer semestre.
energ_GIF = 52000 # 45% por el primer semestre
varios_GIF = 10000 # Anuales

GIFTotal_Sem1 = int((deprec_GIF / 2) + (seguros_GIF / 2) + (mant_GIF * .45) + (energ_GIF * .45) + (varios_GIF / 2))
GIFTotal_Sem2 = int((deprec_GIF / 2) + (seguros_GIF / 2) + (mant_GIF * .55) + (energ_GIF * .55) + (varios_GIF / 2))

print("PRESUPUESTO GASTOS INDIRECTOS DE FABRICACION. ")
print("-"*60)
print("   Material 1.")
t = PrettyTable(['','PRIMER SEMESTRE','SEGUNDO SEMESTRE'])
t.add_row([" Depreciación  ", int(deprec_GIF / 2), int(deprec_GIF / 2)])
t.add_row([" Seguros       ", int(seguros_GIF / 2), int(seguros_GIF / 2)])
t.add_row([" Mantenimiento ",int(mant_GIF * .45), int(mant_GIF * .55)])
t.add_row([" Energeticos   ",int(energ_GIF * .45), int(energ_GIF * .55)])
t.add_row([" Varios        ",int(varios_GIF / 2), int(varios_GIF / 2)])
t.add_row(["(=) Total      ",GIFTotal_Sem1, GIFTotal_Sem2])
print(t)
print("\n")


#9. PRESUPUESTO DE GASTOS DE ADMINISTRACIÓN Y VENTA.
deprec_GAyV = 10000 # Anuales
sueldos_GAyV = 20000 #Anuales
varios_GAyV = 13000 # 45% por el primer semestre
intereses_GAyV = 30000 # Anuales

# Comisiones -> Es el 5% de las Ventas Esperadas por Semestre
ventaTotal_Sem1 = (ventasEsperadas_A1 * precioA_Sem1) +  (ventasEsperadas_B1 * precioB_Sem1) 
ventaTotal_Sem2 = (ventasEsperadas_A2 * precioA_Sem2) +  (ventasEsperadas_B2 * precioB_Sem2) 

GAyVTotal_Sem1 = int((deprec_GAyV / 2) + (sueldos_GAyV / 2) + (ventaTotal_Sem1 * .05) + (varios_GAyV *.45) + (intereses_GAyV / 2))
GAyVTotal_Sem2 = int((deprec_GAyV / 2) + (sueldos_GAyV / 2) + (ventaTotal_Sem1 * .05) + (varios_GAyV *.55) + (intereses_GAyV / 2))

print("PRESUPUESTO DE GASTOS ADM. Y VENTAS.")
t = PrettyTable(['','PRIMER SEMESTRE','SEGUNDO SEMESTRE'])
t.add_row([" Depreciación      ", int(deprec_GAyV /2), int(deprec_GAyV /2)])
t.add_row([" Sueldos y Salarios", int(sueldos_GAyV /2), int(sueldos_GAyV /2)])
t.add_row([" Comisiones        ", int(ventaTotal_Sem1*.05), int(ventaTotal_Sem2 * .05)])
t.add_row([" Varios            ", int(varios_GAyV *.45), int(varios_GAyV *.55)])
t.add_row([" Int. Obligatorios ", int(intereses_GAyV / 2),int(intereses_GAyV / 2)])
t.add_row([" Total",GAyVTotal_Sem1, GAyVTotal_Sem2])
print(t)
print("\n")


#10. DETERMINACIÓN DE COSTOS UNITARIOS.
# Calculo de GIF -> Total de Gastos Indirectos de Fab. / Total de Horas
horasMOTotal = (udsProducir_A1 * cantHoras_A)+ (udsProducir_A2 * cantHoras_A) + (udsProducir_B1 * cantHoras_B) + (udsProducir_B2 * cantHoras_B)
GIF_Total = GIFTotal_Sem1 + GIFTotal_Sem2
GIF = int(GIF_Total / horasMOTotal)

costoxUd_A = (mat1Precio_Sem2 * mat1_A) + (mat2Precio_Sem2 * mat2_A) + (mat3Precio_Sem2 * mat3_A) + (precioHora * cantHoras_A) + (GIF * cantHoras_A)
costoxUd_B = (mat1Precio_Sem2 * mat1_B) + (mat1Precio_Sem2 * mat2_B) + (mat1Precio_Sem2 * mat3_B) + (precioHora * cantHoras_B) + (GIF * cantHoras_B)

print("DETERMICACIÓN DE COSTOS UNITARIOS.")
print("   Producto A.")
t = PrettyTable(['','COSTO','CANTIDAD', 'Costo x ud'])
t.add_row([" Material 1  ", mat1Precio_Sem2, mat1_A, (mat1Precio_Sem2 * mat1_A)])
t.add_row([" Material 2  ", mat2Precio_Sem2, mat2_A, (mat2Precio_Sem2 * mat2_A)])
t.add_row([" Material 3  ", mat3Precio_Sem2, mat3_A, (mat3Precio_Sem2 * mat3_A)])
t.add_row([" Mano de Obra", precioHora, cantHoras_A, (precioHora * cantHoras_A)])
t.add_row([" GIF", GIF, cantHoras_A, (GIF * cantHoras_A) ])
t.add_row([" Total       ",'','',costoxUd_A])
print(t)
print("\n")

print("DETERMICACIÓN DE COSTOS UNITARIOS.")
print(" Producto B.")
t = PrettyTable(['','COSTO','CANTIDAD', 'Costo x ud'])
t.add_row([" Material 1  ", mat1Precio_Sem2, mat1_B, (mat1Precio_Sem2 * mat1_B)])
t.add_row([" Material 2  ", mat2Precio_Sem2, mat2_B, (mat2Precio_Sem2 * mat2_B)])
t.add_row([" Material 2  ", mat3Precio_Sem2, mat3_B, (mat3Precio_Sem2 * mat3_B)])
t.add_row([" Mano de Obra",precioHora, cantHoras_B, (precioHora * cantHoras_B)])
t.add_row([" GIF         ",GIF, cantHoras_B, (precioHora * cantHoras_B) ])
t.add_row([" Total       ",'','', costoxUd_B])
print(t)
print("\n")

# 11. INVENTARIOS FINALES
mat_inventFinal =  (mat1Precio_Sem2 * finalMat1) + (mat2Precio_Sem2 * finalMat2) + (mat3Precio_Sem2 * finalMat3)
print("VALUACIÓN DE INVENTARIOS FINALES")
t = PrettyTable(['','COSTO','CANTIDAD', 'Costo x ud'])
t.add_row([" Material 1  ", mat1Precio_Sem2, finalMat1, (mat1Precio_Sem2 * finalMat1)])
t.add_row([" Material 2  ", mat2Precio_Sem2, finalMat2, (mat2Precio_Sem2 * finalMat2)])
t.add_row([" Material 3  ", mat3Precio_Sem2, finalMat3, (mat3Precio_Sem2 * finalMat3)])
t.add_row([" Total       ",'','',mat_inventFinal])
print(t)
print("\n")


# -> ESTADO DE COSTOS DE PRODUCCIÓN Y DE VENTA.
inventarioMateriales = 80000
inventarioProductos = 150000
mObra_Total = costoMO_Asem1 + costoMO_Asem2 + costoMO_Bsem1 + costoMO_Bsem2
costoVentas = inventarioMateriales + materialTOTAL - mat_inventFinal + mObra_Total + GIF_Total - inventarioProductos

print("ESTADO DE COSTOS DE PROD. Y VENTA.")
t = PrettyTable(['',' '])
t.add_row([" Saldo Inicial de Materiales   ", inventarioMateriales])
t.add_row(["(+) Compra de Materiales       ", materialTOTAL])
t.add_row(["(=) Materiales Disponible      ", (inventarioMateriales + materialTOTAL)])
t.add_row(["(-) Invent. Final de Materiales", mat_inventFinal])
t.add_row(["(=) Materiales Utilizados      ", (inventarioMateriales + materialTOTAL) - mat_inventFinal])
t.add_row(["(+) Mano de Obra               ", mObra_Total])
t.add_row(["(+) Gastos Indirectos de Fab.  ", GIF_Total])
t.add_row(["(=) Costo de Producción        ", (inventarioMateriales + materialTOTAL - mat_inventFinal) + mObra_Total + GIF_Total])
t.add_row(["(-) Invent. Final P.Terminados ", inventarioProductos ])
t.add_row(["(=) Costo de Ventas            ", costoVentas])
print(t)
print("\n")


# -> ESTADO DE RESULTADOS.
gastosOperativos = GAyVTotal_Sem1 + GAyVTotal_Sem2
utilidadOperativa = ventaTotal - materialTOTAL - gastosOperativos
utilidadNETA = int(utilidadOperativa - (utilidadOperativa * .35) - (utilidadOperativa *.10))
print("ESTADO DE RESULTADOS.")
t = PrettyTable(['',' '])
t.add_row(["    Ventas            ", ventaTotal])
t.add_row(["(-) Costo de Ventas   ", materialTOTAL])
t.add_row(["(=) Utilidad Bruta    ", (ventaTotal - materialTOTAL)])
t.add_row(["(-) Gastos Operativos ", gastosOperativos])
t.add_row(["(=) Utilidad Operativa", utilidadOperativa])
t.add_row(["(-) ISR 35%           ", int(utilidadOperativa * .35)])
t.add_row(["(+) PTU 10%           ", int(utilidadOperativa * 10)])
t.add_row(["(=) UTILIDAD NETA     ", utilidadNETA])
print(t)
print("\n")


# FLUJO DE EFECTIVO
cobranzaTotal = 80000 + entradas 
totalSalidas = int(saldoProv + (saldoProv * .6) + mObra_Total + GIF_Total + gastosOperativos + 50000 + 40000 + (utilidadOperativa * .35))
print("FLUJO DE EFECTIVO.")
t = PrettyTable(['',' ', '  '])
t.add_row(["Saldo Inicial      ", '', 40000 ])
t.add_row(["   Cobranza 2020   ", 40000,''])
t.add_row(["   Cobranza 2021   ", entradas,'']) # Presupuesto 2
t.add_row(["TOTAL COBRANZA ",'',cobranzaTotal])
t.add_row(["Salidas            ", '',''])
t.add_row(["   Pago Proveed.20 ", saldoProv,''])
t.add_row(["   Pago Proveed.21 ", int(saldoProv * .6),''])
t.add_row(["   Mano de Obra    ", mObra_Total,''])
t.add_row(["   GIF             ", GIF_Total,''])
t.add_row(["   Gastos de Opera.", gastosOperativos,''])
t.add_row(["   Compra Maquinar.", 50000,''])
t.add_row(["   Pago ISR 2020   ", 40000,''])
t.add_row(["   Pago ISR 202    ", int(utilidadOperativa * .35) ,''])
t.add_row(["TOTAL DE SALIDAS   ", '',totalSalidas])
t.add_row(["FLUJO DE EFECTIVO  ", '',cobranzaTotal - totalSalidas ])
print(t)
print("\n")